"""empty message

Revision ID: 774a5edea88b
Revises: 8c35c255953b
Create Date: 2021-03-13 22:56:22.578604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774a5edea88b'
down_revision = '8c35c255953b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_shows',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_shows')
    # ### end Alembic commands ###
