"""empty message

Revision ID: bcbdc3cc57af
Revises: 774a5edea88b
Create Date: 2021-03-14 14:10:50.115855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbdc3cc57af'
down_revision = '774a5edea88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_shows', sa.Column('start_time', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_shows', 'start_time')
    # ### end Alembic commands ###
